apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-internal-values
  namespace: nginx-ingress-ctrl-internal
data:
  values.yaml: |
    controller:
      image:
        tag: "v0.44.0"
        digest: ""
      publishService:
        enabled: false
      extraArgs:
        publish-status-address: ""
        v: 2
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: ingressClass
                      operator: In
                      values:
                        - nginx-internal
                topologyKey: kubernetes.io/hostname
              weight: 100
      electionID: ingress-controller-leader-nginx-internal
      ingressClass: nginx-internal
      podLabels:
        ingressClass: nginx-internal
      replicaCount: 3
      config:
        use-http2: "true"
        error-log-level: crit
        # disables checking of client request body size
        proxy-body-size: "0"
        server-snippet: |
          more_clear_headers Server;
      resources:
        limits:
          cpu: 300m
          memory: 500Mi
        requests:
          cpu: 150m
          memory: 250Mi
      service:
        type: NodePort
        enableHttp: false
      stats:
        enabled: true
      metrics:
        enabled: true
        service:
          annotations:
            prometheus.io/port: "10254"
            prometheus.io/scrape: "true"
    defaultBackend:
      enabled: true
      replicaCount: 2
      resources:
        limits:
          cpu: 10m
          memory: 20Mi
        requests:
          cpu: 10m
          memory: 20Mi