---
apiVersion: helm.fluxcd.io/v1
kind: Helmhelease
metadata:
  name: nginx-ingress-internal
  namespace: nginx-ingress-internal
spec: 
  releaseName: nginx-ingress-ctrl-internal
  chart:  
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 2.16.0
  valuesFrom:
    - configMapKeyRef:
        name: nginx-ingress-internal-values
        namespace: nginx-ingress-ctrl-internal
        key: values.yaml
        optional: false
        